

SPF: Sender Policy Framework
Used to verify email senders and prevent spoofing

GPO: Group Policy Object
Used in Windows to manage and enforce system/user settings

NAC: Network Access Control
Controls which devices/users can access a network

FIM: File Integrity Monitoring
Detects and tracks changes to files

TPM:Trusted Platform Module
Hardware chip that, securely stores encryption keys,enables secure boot + disk unlock

ACL: Access Control List  
Filters traffic based on IP/port rules. Not designed for detecting exploits or signatures.
    
DLP: Data Loss Prevention 
Focuses on preventing data exfiltration, not exploit detection.

IDS: Intrusion Detection System  
Detects and alerts on attacks (including signature-based), but does NOT block them.

IPS: Intrusion Prevention System 
Detects and actively blocks attacks using signatures.

CSR: Certificate Signing Request  
Used to request a certificate, not validate it

CA: Certificate Authority  
Issues certificates, doesn’t perform live validation

CRC: Cyclic Redundancy Check  
Error-checking for data


OCSP: Online Certificate Status Protocol
Verifies whether a certificate is valid, revoked, or expired,Works in real time when a certificate is presented

CVE: Common Vulnerabilities and Exposures
Unique identifier for publicly known security vulnerabilities.
    
CVSS: Common Vulnerability Scoring System 
Numerical scoring system measuring vulnerability severity (0–10).
                                                           
CIA: Confidentiality, Integrity, Availability
Core principles ensuring data security and system reliability.

CERT: Computer Emergency Response Team
Organization that responds to and manages cybersecurity incidents.

CISO: Chief Information Security Officer
Senior executive responsible for an organization's information security strategy and implementation.

DDoS: Distributed Denial of Service
A cyber attack where multiple compromised systems flood a target with traffic, overwhelming it and causing service disruption.

APT: Advanced Persistent Threat
A prolonged and targeted cyber attack where an intruder gains access to a network and remains undetected for an extended period, often to steal data or cause damage.

UBA: User Behavior Analytics
A cybersecurity process that analyzes user behavior patterns to detect anomalies that may indicate insider threats or compromised accounts.

HIDS: Host-based Intrusion Detection System
A security system that monitors and analyzes the internals of a computing system for signs of malicious activity or policy violations.

NIPS: Network Intrusion Prevention System
A security system that monitors network traffic for suspicious activity and can take action to prevent potential threats.

HSM: Hardware Security Module
A physical device that provides secure generation, storage, and management of cryptographic keys, often used to enhance security in various applications.

WAF: Web Application Firewall
A security system that monitors and filters incoming HTTP traffic to protect web applications from attacks such as SQL injection, cross-site scripting (XSS), and other common web exploits.

NAC: Network Access Control
A security solution that enforces policies to control access to a network, ensuring that only authorized and compliant devices can connect and access resources.

NIDS: Network Intrusion Detection System
A security system that monitors network traffic for signs of malicious activity or policy violations, providing alerts without actively blocking traffic.

P2V: Physical to Virtual
The process of converting a physical machine into a virtual machine, allowing it to run on a virtualization platform.

SAML: Security Assertion Markup Language
An XML-based framework for exchanging authentication and authorization data between parties, commonly used for single sign-on (SSO) implementations.

TOTP: Time-based One-Time Password
A temporary passcode generated by an algorithm that uses the current time as a factor, often used for two-factor authentication (2FA).

Federation: A system that allows users to access multiple applications or systems with a single set of credentials, often implemented using protocols like SAML or OAuth.

Kerboros: A network authentication protocol that uses secret-key cryptography to provide secure authentication for client-server applications.

HOTP: HMAC-based One-Time Password
A temporary passcode generated by an algorithm that uses a counter as a factor, often used for two-factor authentication (2FA).

SOAR: Security Orchestration, Automation, and Response
A set of tools and processes that enable organizations to collect security data, automate responses to incidents, and orchestrate workflows across different security technologies.

